import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import {fetchRedditData} from '../lib/fetch-reddit-data';
import {useState} from 'react';

export async function getStaticProps() {
  const redditData = await fetchRedditData();
  return {
    props: {
      redditData,
    },
  };
}

export default function Home({redditData: initialData}) {
  const [redditData, setRedditData] = useState(initialData);
  const fetchMore = () => {
    fetchRedditData(redditData[redditData.length - 1].name).then((newPosts) => {
      setRedditData([...newPosts]);
    });
    setRedditData([]);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Reddit Feed</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Reddit Feed</h1>

        <div className={styles.grid}>
          {redditData.map((item) => (
            <a
              href={`https://reddit.com${item.permalink}`}
              className={styles.card}
              key={item.name}
              target="_blank"
              rel="noreferrer"
            >
              <h2>{item.title}</h2>
              {/* only show image if it's from i.redd.it */}
              {item.url.includes('i.redd.it') && (
                <Image
                  src={item.url}
                  alt={item.title}
                  width="300"
                  height="300"
                />
              )}
            </a>
          ))}

          <button
            className={styles.card}
            onClick={fetchMore}
            style={{cursor: 'pointer'}}
          >
            Next Page
          </button>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
